apps/cma34cr_ubuntu/src/cross_vm_event.c

I'm trying to build the cma34cr_ubuntu app, but I get a compile error unless I remove this cast.

removing cast prevents compile error

---

components/Init/src/main.c

This PR contains commits from Dornerworks' x64 VM patches for camkes-vm: https://github.com/dornerworks/camkes-vm/tree/open_source_release. Only parts of https://github.com/dornerworks/camkes-vm/commit/1cd3916eacf4c0120192f78ef1ea39d5c87e9cc3 were taken. The HPET emulation requires slightly more work due to the new refactored VMMs having a different model for memory faults.

Dornerworks x64 VM patches

---

components/VM_Arm/plat_include/tx1/plat/vmlinux.h
components/VM_Arm/plat_include/tx2/plat/vmlinux.h

The previous declaration was declaring a type `IRQConstants` and (mistakenly) a variable `platform_interrupt_t`. Neither name is referenced in the rest of the code and `platform_interrupt_t` is the better name for the type.

vmlinux.h: fix enum declaration

---

components/Init/src/virtio_net.c
components/Init/src/virtio_net_vswitch.c
libs/libvirtio/src/virtio_net.c

libsel4vmmplatsupport: fix PCI passthrough on ARM
ARM uses the same PCI BAR emulation as x86 now.
Signed-off-by: Hannu Lyytinen <hannux@ssrc.tii.ae>
Test with: seL4/seL4_projects_libs#25

libsel4vmmplatsupport: fix PCI passthrough on ARM

---

components/Init/src/main.c

the upper bound of {0x500, 0x7c00 - 0x500} and the lower bound of
{0x7e00, 0x80000 - 0x7e00} belong to the same page. Merging them
to avoid vspace reservation failing.

init: merge two `guest_ram_regions` into one

---

CMakeLists.txt
components/Init/Init.camkes
components/Init/src/virtio_blk.c
components/Init/src/virtio_blk.h
components/Sataserver/CMakeLists.txt
components/Sataserver/Sataserver.camkes
components/Sataserver/include/plat/empty/plat/sata.h
components/Sataserver/include/plat/pc99/optiplex/plat/sata.h
components/Sataserver/include/sataserver.h
components/Sataserver/src/sataserver.c
components/VM/configurations/sata.h
components/VM/vm.camkes
interfaces/Sataserver.idl4
templates/seL4Sataserver-from.template.c
templates/seL4Sataserver-to.template.c

This commit combines a number of smaller commits which do the following:
* Add sataserver component and supporting files
* Convert sataserver to the latest CAmkES release and cmake
* Fix io ops memory issue in sataserver post init
* Fixed virtio blk dma alignment to work on both 64 bit and 32 bit hosts
* Force virtio blk request to a max of 4096 bytes
* Update structs to follow changes made in libsatadrivers
* Adapt Sataserver to AHCI changes in libsatadrivers
* Add sataserver hardware configuration based on machine
* Update templates to run without threads
* Add CHS values to virtual MBR partition entries
* Fix virtual capacity calculation
* Lock sataserver sooner on client rx and tx calls
* Virtualize the MBR
* Add case for all possible directions
* Connect to serial server
* Update …

sataserver: Add sataserver component and support

---

camkes_vm_helpers.cmake

It seems `basename` was intended to make `filename_pref` an optional parameter, but this was never implemented. Removing this for now,. can be brought back in case this features will be added again.
With https://github.com/Hensoldt-Cyber/camkes-vm/commits/patch-axel-5 we are working on a PR where `DefineCAmkESVMFileServer()` can also take an optional file parameters, so there is no need to call `AddToFileServer()`. This supports omitting a file name for the CPIO archive and will use the base name then.

CMake: remove unused variable

---

components/Init/templates/seL4VMIRQs.template.c

The previous template does not handle more than one IOAPICs.
Signed-off-by: Jingyao Zhou <jingyao.zhou@unsw.edu.au>

Init: update seL4VMIRQs to allow multiple IOAPICs

---

components/VM_Arm/src/main.c
templates/seL4VMDTBPassthrough-to.template.c

Adds "vm-specific" plat_keep_devices and plat_keep_devices_and_subtree entries that can be defined in the devices.camkes file. Allows for more customization of device tree generation.

Device Tree Generation Fixes

---

components/VM_Arm/configurations/vm.h
components/VM_Arm/src/main.c

When generating a device tree, the default behavior is to use the kernel device tree, which is passed down through the bootinfo struct. This works for some platforms, however, there are platforms where the bootloader or toolchain updates modify the device tree. In these cases, the dts in the kernel is not a usable base for a generated device tree.
This commit adds an option "VmCustomDtbBase" which when enabled will ignore the kernel device tree, and instead pull the linux_image_config.dtb_base defined in the CAmkES configuration from the File Server. This based is used as the fdt_ori pointer during the fdt generation process.
This option provides an alternative to updating the kernel device tree, keeping that file from changing everytime a toolchain updates.
Signed-off-by: Chris Guikema …

vm_arm: add option for custom device tree base

---

arm_vm_helpers.cmake
components/VM_Arm/src/main.c
templates/seL4AllocatorMempool.template.c
templates/seL4AllocatorMempool.template.h

The size of the allocator_mempool determines, along with the number of untyped objects, how much RAM a VM can map. There is also a circumstance on a 2VM system where VM0 needs to map a lot of RAM, and VM1 needs to map a little. The current setup would require the user to increase the allocator_mempool buffer for each VM, wasting system resources.
This commit adds a new template that defines the allocator_mempool buffer. Simply put "vm0.allocator_mempool_size = X" in the configuration to set the mempool size. This allows each VM to configure the mempool for its own needs, which more efficiently utilizes system resources.

vm_arm: add allocator mempool template

---

components/VM_Arm/src/main.c

Trying to open an empty file will trigger this warning: sys_open_impl@sys_io.c:192 Failed to open file
This commit checks if the dtb_base_name is an empty string before attempting to open it.

trivial: check dtb_base_name before open

---

components/VM_Arm/plat_include/exynos5410/plat/vmlinux.h
components/VM_Arm/plat_include/exynos5422/plat/vmlinux.h
components/VM_Arm/plat_include/odroidc2/plat/vmlinux.h
components/VM_Arm/plat_include/qemu-arm-virt/plat/vmlinux.h
components/VM_Arm/plat_include/tk1/plat/vmlinux.h
components/VM_Arm/plat_include/tx1/plat/vmlinux.h
components/VM_Arm/plat_include/tx2/plat/vmlinux.h
components/VM_Arm/src/main.c

This commit defines the gic path for each platform, which is used to parse the device tree to find the gic phandle, instead of relying on the user to provide the correct value.
I could use some help to validate that this functions properly. I did my best to find the proper gic for each platform, but I may have messed things up.
https://github.com/seL4/camkes-vm/issues/49

vm_arm: use gic path to find phandle

---

components/VM_Arm/src/main.c

Previously, the following prints would appear for any RAM-backed device install:
alloc_vm_device_cap@main.c:1011 Grabbing the entire cap for device memory 
alloc_vm_device_cap@main.c:1014 Failed to grab the entire cap
To an unexperienced user, this could cause confusion as to what is happening in the VMM. This commit reduces the verbosity of some prints, and adds prints to clarify the region mapped, and whether it is RAM backed or device backed.
Signed-off-by: Chris Guikema <chris.guikema@dornerworks.com>

vm_arm: clarify on-demand device prints

---

arm_vm_helpers.cmake
components/VM_Arm/CMakeLists.txt
components/VM_Arm/plat_include/ultra96v2/plat/vmlinux.h
components/VM_Arm/plat_include/zynqmp/plat/vmlinux.h
components/VM_Arm/src/modules/vuart_init.c
libs/libvirtio/plat_include/zynqmp/virtio/virtio_plat.h

Add support for compiling a zynqmp VMM. Example projects can be added to camkes-vm-examples once the SMC RFC has been worked through. This just adds the structure for the zynqmp.

Zynqmp vmm

---

components/Init/src/i8254.c
components/Init/src/main.c
components/Init/src/mc146818rtc.c
components/Init/src/serial.c
components/Init/src/virtio_blk.c
components/Init/src/virtio_con.c
components/Init/src/virtio_con.h
components/Init/src/virtio_irq.h
components/Init/src/virtio_net.c
components/Init/src/virtio_net_vswitch.c
components/Init/src/virtio_net_vswitch.h
components/Init/src/virtio_vsock.c
components/Init/src/virtio_vsock.h
components/Sataserver/include/plat/pc99/supermicro/plat/sata.h
components/VM/configurations/vm.h
components/VM_Arm/configurations/vm.h
libs/libvirtio/include/virtioarm/virtio_console.h
libs/libvirtio/src/virtio_console.c

This modifies the virtio console to support multiplexing, as well as add a new virtio vsock device.
Test with: https://github.com/seL4/seL4_projects_libs/pull/88 and https://github.com/seL4/camkes-tool/pull/118

virtio: console multiplex and vsock support

---

components/VM_Arm/configurations/vm.h

Sets getchar_clients to be their VM number.
Test with: seL4/global-components#40

vm_arm, trivial: align serial inputs to vm number

---

arm_vm_helpers.cmake
components/VM_Arm/configurations/vm.h
components/VM_Arm/docs/vm_memory_configuration.md
components/VM_Arm/plat_include/exynos5410/plat/vmlinux.h
components/VM_Arm/plat_include/exynos5422/plat/vmlinux.h
components/VM_Arm/plat_include/qemu-arm-virt/plat/vmlinux.h
components/VM_Arm/plat_include/tk1/plat/vmlinux.h
components/VM_Arm/plat_include/tx1/plat/vmlinux.h
components/VM_Arm/plat_include/tx2/plat/vmlinux.h
components/VM_Arm/src/main.c
components/VM_Arm/src/modules/init_ram.c
templates/seL4VMParameters.template.c
templates/seL4VMParameters.template.h

Test with: https://github.com/seL4/seL4_projects_libs/pull/81
Test with: https://github.com/seL4/camkes-vm-examples/pull/31

Multiple OS Support

---

components/VM_Arm/src/main.c

Seems these are some artifacts that came over with the migration of this file, but they have never been used here.

vm_arm: remove unused defines

---

components/VM_Arm/plat_include/exynos5410/plat/vmlinux.h
components/VM_Arm/plat_include/exynos5422/plat/vmlinux.h
components/VM_Arm/plat_include/qemu-arm-virt/plat/vmlinux.h
components/VM_Arm/plat_include/tk1/plat/vmlinux.h
components/VM_Arm/plat_include/tx1/plat/vmlinux.h
components/VM_Arm/plat_include/tx2/plat/vmlinux.h

Avoid some redundancy by reusing the define `GIC_NODE_PATH`

vm_arm: reuse define GIC_NODE_PATH

---

components/VM_Arm/configurations/vm.h
templates/seL4VMParameters.template.c
templates/seL4VMParameters.template.h

Remove unused attic variables as a follow-up from the changes https://github.com/seL4/camkes-vm/pull/48 brought in. Also set a dummy default configuration, so they don't have to be specified in new configurations files in case the deprecated config block `linux_address_config` is used.

vm_arm: remove unused attic variables

---

components/VM_Arm/src/main.c

Keep the semantics, that files are closed. And that they are closed as soon as possible, so resources are not locked longer than necessary. This also drop the assumption here, that this is a fatal error that leads to application termination anyway.

vm_arm: close DTB file also in case of error

---

components/VM_Arm/src/main.c

The function is used internally only, so there is no need to expose it.

vm_arm: make function static

---

components/VM_Arm/src/main.c
components/VM_Arm/src/modules/init_ram.c
templates/seL4VMParameters.template.c
templates/seL4VMParameters.template.h

- Groups config variables in struct to emulate a namespace, this avoids polluting the global name space. 
- Pass config down to make the code a bit more generic
- Add a helper function to improve code readability a bit

Groups config variables in struct to emulate a namespace

---

components/VM_Arm/src/fdt_manipulation.c
components/VM_Arm/src/fdt_manipulation.h
templates/seL4VMParameters.template.h

Basically https://github.com/seL4/camkes-vm/pull/58 from @hlyytine reworked to the recent changes. Best to merge after https://github.com/seL4/camkes-vm/pull/60 is in, then the unused variables `linux_ram_offset` and `initrd_max_size` are gone already

vm_arm: use more specific integer types

---

components/VM_Arm/include/vmlinux.h
components/VM_Arm/src/main.c

Allow generating DTB on the fly when the VM is created/manipulated. This also allows modules to manipulate it.
This partly overlaps with what https://github.com/seL4/camkes-vm/pull/70 is doing.

vm_arm: make DTB generation more flexible

---

components/Init/src/main.c
components/VM_Arm/src/main.c

- `simple_get_untyped_count()` can return an error code.
- `camkes_dtb_untyped_count()` may also return an error, given the current signature does not specify it only returns unsigned integers.

vm_arm: check return codes properly

---

.github/workflows/test.yml

Provide the PR commit sha, otherwise the test will just run on the master branch.

github: provide PR sha for hardware test

---

components/VM_Arm/src/modules/virtio_net_virtqueue.c

Use proper types to avoid build warnings.
```
Building C object components/VM_Arm/src/modules/virtio_net_virtqueue.c.obj
components/VM_Arm/src/modules/virtio_net_virtqueue.c: 
In function 'virtio_net_notify_free_send':
components/VM_Arm/src/modules/virtio_net_virtqueue.c:76:73: 
warning: passing argument 3 of 'virtqueue_get_used_buf' from incompatible pointer type [-Wincompatible-pointer-types]
76 |     while (virtqueue_get_used_buf(node->virtqueues.send_queue, &handle, &wr_len)) {
|                                                                         ^~~~~~~
|                                                                         |
|                                                                         size_t * {aka long unsigned int *}
In file included from …
```

vm_arm: use proper types to avoid build warnings

---

camkes_vm_helpers.cmake

- allow custom type and instance names
- allow passing files for `DefineCAmkESVMFileServer()`, this avoids calling `AddToFileServer()`
- `AddToFileServer()` becomes just a light wrapper
- use instance specific name for archive and lib
This allows doing customizing the file server component name and doing all in one call:
```
DefineCAmkESVMFileServer(
INSTANCE "myFileServer"
FILES
"linux:${VM_IMG_LINUX}"
"linux-initrd:${VM_IMG_ROOTFS}"
"linux-dtb:${VM_IMG_DTB_PATCHED}"
DEPENDS
target_dtb_gen
)
```
See https://github.com/seL4/camkes-vm-examples/pull/37 for a usage examples.

make DefineCAmkESVMFileServer() more flexible

---

libs/libvirtio/src/virtio_console.c
libs/libvirtio/src/virtio_net.c

It might not matter much for the current use cases, but it's good practice to free memory that was allocated.

libvirtio: free memory on error

---

libs/libvirtio/include/virtioarm/virtio_console.h

Including virtqueue.h seems a bit odd, because the API does not need it. If implementations need it eventually, they have to include it.
This is basically PR https://github.com/seL4/camkes-vm/pull/104, but I had some rebase quirk that eventually deleted the branch, so the other PR got closed.

libvirtio: remove unused include

---

components/VM_Arm/src/main.c

The macro already creates a line break

vm_arm: remove line break in ZF_LOGx()

---

components/VM_Arm/src/main.c

Add a new capability which certain threads can invoke so seL4 can make SMC calls on ARM platforms in EL2 (virtualized mode) on the thread’s behalf.
See https://sel4.atlassian.net/browse/RFC-9
This is dependent on these changes: https://github.com/seL4/seL4_projects_libs/pull/24 So it shouldn't be merged until that one is.

SMC Capability

---

components/Init/src/main.c

Kernel relocations are not needed with 64-bit guest kernels. This commit allows for vm0.kernel_relocs = "" to specify no relocation is needed.

init, trivial: allow for relocs to be optional

---

components/VM_Arm/plat_include/ultra96v2/plat/vmlinux.h
components/VM_Arm/plat_include/zynqmp/plat/vmlinux.h

This is basically what we did in https://github.com/seL4/camkes-vm/pull/94 also, if we do not provide these peripherals, some basic use cases do not work. So it seem best to always provide them here.

vm_arm: provide GIC and timer to VM on zynqmp

---

components/VM_Arm/CMakeLists.txt
components/VM_Arm/plat_include/ultra96v2/plat/smc.h
components/VM_Arm/plat_include/zynqmp/plat/smc.h

Add an SMC header for the zynqmp platform. This allows the SMC capability to look nice in the configuration.
```
vm0.allowed_smc_functions = [
PM_GET_API_VERSION,
PM_REQUEST_NODE,
PM_RELEASE_NODE,
PM_SET_REQUIREMENT,
PM_INIT_FINALIZE,
PM_FPGA_GET_STATUS,
```

smc: Add header for plat specfic smc calls

---

templates/seL4VMParameters.template.c

Having `config` as a variable to use comes really helpful in a lot of other patches that extend the config data. Any chance to get this merged, as it's a trivial change to improve usability?

vm_arm: reduce redundancy in template

---

components/VM_Arm/CMakeLists.txt
components/VM_Arm/plat_include/zynqmp/plat/vmlinux.h

Test with: https://github.com/seL4/camkes-vm-examples/pull/57

Zynqmp 2018 3

---

.github/workflows/test.yml

Apply what has been done in 
- https://github.com/seL4/camkes-vm-examples/pull/61
- https://github.com/seL4/camkes-vm-examples/pull/69

apply CI updates that were done in other repos also

---

components/VM_Arm/CMakeLists.txt
components/VM_Arm/plat_include/zynqmp/plat/smc.h

Couple small commits to support running Petalinux 2022.1 in the camkes-vm.

Zynqmp 2022 1
